"""Shared Arkanoid dimensions and tuning values."""

BOARD_WIDTH = 76
BOARD_HEIGHT = 24
HUD_HEIGHT = 3
PLAY_TOP = HUD_HEIGHT
PADDLE_WIDTH = 9
PADDLE_ROW = BOARD_HEIGHT - 2
BALL_START_X = BOARD_WIDTH // 2
BALL_START_Y = PADDLE_ROW - 1
BALL_SPEED = 1
BRICK_ROWS = 5
BRICK_COLUMNS = 11
BRICK_WIDTH = 6
BRICK_GAP = 1
BRICK_TOP = PLAY_TOP + 2
TICK_SECONDS = 0.07
STARTING_LIVES = 3
