"""Shared settings for ShellSpaceInvaders."""

WIDTH = 60
HEIGHT = 24
PLAYER_Y = HEIGHT - 2
PLAYER_START_X = WIDTH // 2
PLAYER_SPEED = 2
ENEMY_ROWS = 4
ENEMY_COLUMNS = 8
ENEMY_START_Y = 3
ENEMY_X_GAP = 5
ENEMY_Y_GAP = 2
WINNING_WAVE = 5
FRAME_DELAY = 0.05
ENEMY_STEP_EVERY = 3
ENEMY_FIRE_EVERY = 15
