"""Shared settings for ShellFlappyBird."""

WIDTH = 60
HEIGHT = 24
GROUND_Y = HEIGHT - 2
BIRD_X = 14
BIRD_START_Y = HEIGHT // 2
PIPE_WIDTH = 4
PIPE_GAP = 7
PIPE_SPACING = 24
GRAVITY = 0.28
FLAP_VELOCITY = -1.8
FRAME_DELAY = 0.05
